- name: Run agent CLI tool
  env:
    ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
  run: |
    # Create a prompt that includes the context and best practices
    cat > agent_prompt.txt << 'EOL'
    GitHub Issue #${{ github.event.issue.number }}: ${{ github.event.issue.title }}
    
    ISSUE DESCRIPTION:
    ${{ github.event.issue.body }}
    
    REPOSITORY CONTEXT:
    This is running in a GitHub Action triggered by an issue. 
    Repository: ${{ github.repository }}
    
    BEST PRACTICES:
    - Try to get as far as you can agentically with the task
    - Read the project README and find out how to execute tests
    - Do TDD if possible
    - No need to push changes, just make them locally
    - Make sure to understand the codebase structure before making changes
    - Run tests after making changes to verify functionality
    - Follow the project's coding style guidelines
    
    INSTRUCTIONS:
    Please implement the requested changes based on the issue description.
    EOL
    
    # Run Claude Code with the prepared prompt (with verbose flag)
    claude -p "$(cat agent_prompt.txt)" --verbose