name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      prompt:
        required: true
        description: What do you want Claude to do?

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", "🥳"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"
